dimitri:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: abdomen_joint
    pid: {p: 1000.0, i: 0.01, d: 100.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: abdomen_upper_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_gripper_joint
    pid: {p: 1.0, i: 0.01, d: 0.01}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_gripper_joint
    pid: {p: 1.0, i: 0.01, d: 0.01}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_hand_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_shoulder_joint
    pid: {p: 1000.0, i: 0.001, d: 0.01}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_under_arm_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_upper_arm_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}
  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wrist_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: neck_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_gripper_joint
    pid: {p: 1.0, i: 0.01, d: 0.01}
  joint13_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_gripper_joint
    pid: {p: 1.0, i: 0.01, d: 0.01}
  joint14_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_hand_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}
  joint15_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_shoulder_joint
    pid: {p: 1000.0, i: 0.001, d: 0.01}
  joint16_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_under_arm_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}
  joint17_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_upper_arm_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}
  joint18_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wrist_joint
    pid: {p: 1000.0, i: 0.01, d: 0.01}


