dimitri:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: abdomen_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: abdomen_upper_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_gripper_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_gripper
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_hand_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_shoulder_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_under_arm_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_upper_arm_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wrist_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: neck_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_gripper_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint13_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_gripper_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint14_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_hand_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint15_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_shoulder_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint16_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_under_arm_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint17_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_upper_arm_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint18_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wrist_link
    pid: {p: 100.0, i: 0.01, d: 10.0}


